<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1634339656013' stop='1634339716021'>
    <name>Add Appointment</name>
    <title>Add Appointment</title>
    <test-cases>
        <test-case start='1634339656013' status='broken' stop='1634339716020'>
            <name>should open appointment link</name>
            <title>should open appointment link</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-94.0.4606.81'/>
            </parameters>
            <steps>
                <step start='1634339656014' status='broken' stop='1634339716020'>
                    <name>POST /session/:sessionId/url</name>
                    <title>POST /session/:sessionId/url</title>
                    <attachments>
                        <attachment title='Request' source='b5fefa2c-d633-45fe-ab4d-142d7a5fbc3a-attachment.json' type='application/json' size='58'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Timeout of 60000ms exceeded. The execution in the test "Add Appointment should open appointment link" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/Users/nanmeng/Documents/PracticeForMichelle/test/specs/appointment.spec.js)</message>
                <stack-trace>Error: Timeout of 60000ms exceeded. The execution in the test "Add Appointment should open appointment link" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/Users/nanmeng/Documents/PracticeForMichelle/test/specs/appointment.spec.js)
                    at createTimeoutError (/Users/nanmeng/Documents/PracticeForMichelle/node_modules/mocha/lib/errors.js:498:15)
                    at Test.Runnable._timeoutError (/Users/nanmeng/Documents/PracticeForMichelle/node_modules/mocha/lib/runnable.js:431:10)
                    at Timeout.&lt;anonymous> (/Users/nanmeng/Documents/PracticeForMichelle/node_modules/mocha/lib/runnable.js:246:24)
                    at listOnTimeout (node:internal/timers:557:17)
                    at processTimers (node:internal/timers:500:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>